import type { SeoLandingData } from '@/components/home/SeoLanding';

// All SEO landing pages share the same component but carry different copy
// and schema. Keeping data centralised lets us cross-link them trivially.

export const qrMenuPage: SeoLandingData = {
    slug: 'qr-menu',
    h1: 'QR Code Menu for Restaurants in India',
    subtitle:
        'Give every table a QR code that opens your menu in 2 seconds — no app download, no waiter needed, no printing cost. Live in 3 minutes with vsite.',
    features: [
        { icon: 'qr_code_2', title: 'Unique QR Per Table', description: 'Each table gets its own QR code so orders arrive tagged with the table number automatically.' },
        { icon: 'bolt', title: 'Opens in 2 Seconds', description: 'Customers scan with the native camera app. Your menu loads instantly — no app download required.' },
        { icon: 'edit', title: 'Real-Time Menu Edits', description: 'Change prices, mark items out of stock, add daily specials from your phone. No reprinting ever.' },
        { icon: 'translate', title: 'Tamil + English', description: 'Customers toggle between languages with one tap. Built for South Indian restaurants.' },
        { icon: 'image', title: 'AI Food Photos', description: 'Every item gets a professional food photo generated by AI — no photographer, no shoot.' },
        { icon: 'payments', title: 'UPI Payment at Table', description: 'Optional: customers pay via PhonePe/GPay/Paytm at the table. Zero commission.' },
    ],
    content: [
        { type: 'p', text: 'A QR code menu lets your customers scan a printed code on the table and instantly view your restaurant\'s full menu on their own phone. With vsite, you get a unique QR code per table, AI-generated food photos for every item, and Tamil-language support — all live in under 3 minutes.' },
        { type: 'h2', text: 'Why Every Indian Restaurant Needs a QR Menu in 2026' },
        { type: 'p', text: 'Post-COVID, 60%+ of urban restaurants in India have switched to QR menus. The reasons are economic: eliminating paper menu printing saves ₹10,000–₹25,000 per year, and photo-rich menus increase average order value by 10–20%. For the customer, it\'s faster, cleaner, and doesn\'t require downloading yet another app.' },
        { type: 'h2', text: 'How a QR Code Menu Works with vsite' },
        { type: 'ol', items: [
            'You photograph your paper menu and upload it to vsite',
            'Our AI reads every item, price, and category — including Tamil text',
            'AI generates a professional food photo for each dish',
            'You get a QR code for each table plus a physical NFC card',
            'Customers scan → menu opens → they order → you fulfil',
        ]},
        { type: 'h2', text: 'What Makes vsite\'s QR Menu Different' },
        { type: 'table', headers: ['Feature', 'vsite', 'Typical QR Menu Tool'], rows: [
            ['Setup time', '3 minutes', '1–2 days'],
            ['AI food photos', 'Included', 'Not offered'],
            ['Tamil language', 'Built-in toggle', 'English only'],
            ['NFC card included', 'Yes', 'No'],
            ['Monthly cost', '₹399', '₹500 – ₹1,500'],
            ['Per-order commission', 'None', '1.5% – 3%'],
        ]},
        { type: 'callout', text: 'vsite is the only QR menu tool in India built specifically for Tamil Nadu restaurants — Tamil support, ₹399/mo, and AI-generated food photos included.' },
    ],
    relatedLinks: [
        { label: 'Digital Menu for Indian Restaurants →', href: '/digital-menu-india' },
        { label: 'AI Menu Builder →', href: '/ai-menu-builder' },
        { label: 'Restaurant Menu Software →', href: '/restaurant-menu-software' },
        { label: 'Pricing →', href: '/pricing' },
        { label: 'Features →', href: '/features' },
        { label: 'How to Create a QR Code Menu →', href: '/blog/how-to-create-qr-code-menu-restaurant' },
        { label: 'NFC vs QR Code Menus →', href: '/blog/nfc-vs-qr-code-restaurant-menus' },
    ],
    faqs: [
        { q: 'How do I create a QR code menu for my restaurant?', a: 'Sign up on vsite.in, upload a photo of your paper menu, and vsite\'s AI builds your digital menu with food photos automatically. You get a QR code and NFC card to display on your tables. The entire process takes under 3 minutes.' },
        { q: 'Do customers need to download an app to scan a QR menu?', a: 'No. Customers use their phone\'s native camera app to scan the QR code. The menu opens in their browser within 2–3 seconds. No app download, no signup, no friction.' },
        { q: 'How much does a QR code menu cost in India?', a: 'vsite\'s QR Menu plan costs ₹399/month with a one-time setup fee of ₹1,999. This includes AI food photos, unlimited menu updates, a physical NFC card, and WhatsApp support. Competitors typically charge ₹500–₹1,500/month.' },
        { q: 'Can I have a unique QR code for each table?', a: 'Yes. vsite generates a unique QR code per table so orders arrive tagged with the correct table number. This eliminates verbal order-taking and reduces errors.' },
        { q: 'Does the QR menu work without internet on the customer\'s side?', a: 'Customers need mobile data or Wi-Fi to open the menu the first time. Once loaded, the menu runs entirely in their browser and works even on slow 4G connections.' },
    ],
};

export const digitalMenuIndiaPage: SeoLandingData = {
    slug: 'digital-menu-india',
    h1: 'Digital Menu for Restaurants in India',
    subtitle:
        'A digital menu that understands Indian restaurants — Tamil language, ₹399/month pricing, AI food photos, and UPI payment built in. Join hundreds of restaurants across Tamil Nadu on vsite.',
    features: [
        { icon: 'smartphone', title: 'Works on Every Phone', description: 'Opens in any smartphone browser — Android, iPhone, even basic 4G phones.' },
        { icon: 'autorenew', title: 'Update Anytime', description: 'Change prices, add specials, mark out-of-stock items in real time from your phone.' },
        { icon: 'language', title: 'Tamil + English', description: 'Serve Tamil-speaking and English-speaking customers from the same menu with one tap.' },
        { icon: 'insights', title: 'Built-In Analytics', description: 'See which dishes get the most views, your busiest times, and top-selling categories.' },
        { icon: 'receipt_long', title: 'Zero Commission', description: 'Unlike Zomato or Swiggy, you keep 100% of every order. No middleman fees.' },
        { icon: 'support_agent', title: 'WhatsApp Support', description: 'Real humans on WhatsApp respond within 2 hours. No chatbots, no ticket queues.' },
    ],
    content: [
        { type: 'p', text: 'A digital menu is an online version of your restaurant\'s paper menu that customers view on their smartphone by scanning a QR code. For Indian restaurants in 2026, digital menus have become the default — eliminating printing costs, enabling real-time price changes, and improving the customer experience.' },
        { type: 'h2', text: 'Why Digital Menus Are Winning in India' },
        { type: 'ul', items: [
            'The Indian food delivery market is on track for $12 billion by 2026',
            '96% of QR code scans happen on mobile — every Indian customer has the tech',
            '500 million+ Indians use UPI daily — paying at the table is now natural',
            'Restaurants with photo-rich digital menus see 10–20% higher average order value',
            'Printing a paper menu set costs ₹500–₹2,000; most restaurants reprint 2–4 times a year',
        ]},
        { type: 'h2', text: 'What to Look for in a Digital Menu Tool for India' },
        { type: 'ol', items: [
            'Tamil (and ideally Hindi) language support — most tools are English-only',
            'Price point suited to Indian SMB restaurants — not enterprise POS prices',
            'UPI payment integration — Indian customers expect to pay from their phone',
            'Zero per-order commission — commission models compound fast at Indian ticket sizes',
            'AI food photo generation — most Indian restaurants cannot afford a food photo shoot',
            'Live in minutes — Indian restaurant owners don\'t have time for 2-day onboarding',
        ]},
        { type: 'h2', text: 'vsite vs Alternatives' },
        { type: 'table', headers: ['Tool', 'Price', 'Tamil', 'AI Photos', 'Commission'], rows: [
            ['vsite', '₹399/mo', 'Yes', 'Yes', 'None'],
            ['Petpooja', '₹10,000+/yr', 'Partial', 'No', '1.5%'],
            ['DotPe', 'Commission %', 'No', 'No', 'Varies'],
            ['MakeMyMenu', 'Freemium', 'No', 'No', 'None'],
            ['MenuGen', 'Low cost', 'No', 'No', 'None'],
        ]},
        { type: 'callout', text: 'vsite is the only digital menu platform built specifically for Tamil Nadu restaurants. 14-day free trial. No credit card.' },
    ],
    relatedLinks: [
        { label: 'QR Code Menu →', href: '/qr-menu' },
        { label: 'AI Menu Builder →', href: '/ai-menu-builder' },
        { label: 'Restaurant Menu Software →', href: '/restaurant-menu-software' },
        { label: 'Pricing →', href: '/pricing' },
        { label: 'Features →', href: '/features' },
        { label: 'Best Digital Menu Software in India 2026 →', href: '/blog/best-digital-menu-software-india-2026' },
        { label: 'Paper Menu vs Digital Menu Cost →', href: '/blog/paper-menu-vs-digital-menu-india' },
    ],
    faqs: [
        { q: 'What is a digital menu for restaurants?', a: 'A digital menu is an online version of your restaurant\'s menu that customers view on their smartphone — usually by scanning a QR code on the table. There is no app to download; the menu opens instantly in any browser and can show photos, prices, and a direct ordering button.' },
        { q: 'Which is the best digital menu software for restaurants in India?', a: 'For small and medium restaurants, especially in Tamil Nadu, vsite is the best option in 2026. It costs ₹399/month, includes AI-generated food photos, supports Tamil, and goes live in 3 minutes. For large multi-outlet chains, Petpooja\'s full POS may suit better despite higher cost.' },
        { q: 'How much does a digital menu cost in India?', a: 'Digital menus in India cost between ₹399 and ₹1,500 per month. vsite offers a QR Menu plan at ₹399/month with a one-time setup fee of ₹1,999 — one of the most affordable credible options in 2026.' },
        { q: 'Can I accept online orders through a digital menu?', a: 'Yes. vsite\'s Pay & Eat plan lets customers place orders and pay via UPI directly from the digital menu. Orders fire to your kitchen dashboard in real time. Zero commission on orders.' },
        { q: 'Does a digital menu work in Tamil?', a: 'vsite supports Tamil and English menus with a one-tap toggle. You can run your menu in Tamil, English, or both simultaneously. No competitor offers this.' },
    ],
};

export const aiMenuBuilderPage: SeoLandingData = {
    slug: 'ai-menu-builder',
    h1: 'AI Menu Builder for Restaurants',
    subtitle:
        'Upload a photo of your paper menu. Our AI reads every dish, every price, every Tamil word — and builds your digital menu with professional food photos in 3 minutes.',
    features: [
        { icon: 'auto_awesome', title: 'AI Menu Extraction', description: 'Photograph your paper menu. AI reads item names, prices, and categories — including Tamil text.' },
        { icon: 'photo_camera', title: 'AI Food Photos', description: 'Every item gets a matched professional food photo automatically. No shoot, no photographer.' },
        { icon: 'schedule', title: '3-Minute Setup', description: 'From uploading your paper menu to a live QR code — under 3 minutes end to end.' },
        { icon: 'translate', title: 'Tamil OCR', description: 'The AI recognises Tamil script and mixed Tamil-English menus — unique in India.' },
        { icon: 'edit', title: 'Edit Anything After', description: 'AI gets you 90% of the way. Fine-tune prices, swap photos, re-categorise in the dashboard.' },
        { icon: 'shield', title: 'Your Data, Your Menu', description: 'We don\'t share menus with anyone. Your restaurant data belongs only to you.' },
    ],
    content: [
        { type: 'p', text: 'vsite\'s AI menu builder is the only tool in India that creates a professional digital menu from a photo of your paper menu in under 3 minutes. The AI reads your menu, matches professional food photos to every dish, and publishes a branded QR code menu — automatically.' },
        { type: 'h2', text: 'What the AI Does Step-by-Step' },
        { type: 'ol', items: [
            'Reads the uploaded image using OCR trained on Indian menu formats (English + Tamil)',
            'Extracts dish names, prices, categories, and descriptive text',
            'Matches each dish to a professional food photo from a vetted library',
            'Structures the menu into a branded, mobile-first digital layout',
            'Generates your unique vsite URL and QR code',
        ]},
        { type: 'h2', text: 'Why Use AI Instead of Manual Entry' },
        { type: 'ul', items: [
            'Speed — 3 minutes vs 2+ hours typing item by item',
            'Accuracy — AI rarely mistypes prices; humans do frequently',
            'Tamil support — most menu builders cannot read Tamil at all',
            'Food photos — AI matching is free; a photo shoot costs ₹5,000–₹15,000',
            'Consistency — every dish gets a polished photo; manual entry leaves gaps',
        ]},
        { type: 'callout', text: 'No other digital menu tool in India uses AI to read your paper menu and generate photos automatically. This is vsite\'s unique capability.' },
    ],
    relatedLinks: [
        { label: 'QR Code Menu →', href: '/qr-menu' },
        { label: 'Digital Menu for Restaurants in India →', href: '/digital-menu-india' },
        { label: 'Restaurant Menu Software →', href: '/restaurant-menu-software' },
        { label: 'Features →', href: '/features' },
        { label: 'Pricing →', href: '/pricing' },
        { label: 'How Tamil Nadu Restaurants Use AI Menus →', href: '/blog/tamil-nadu-restaurants-ai-menus' },
    ],
    faqs: [
        { q: 'How does an AI menu builder work?', a: 'You upload a photo of your paper menu. The AI uses OCR to read every item, price, and category — including Tamil text. It then matches each dish to a professional food photo and publishes your full digital menu automatically. The process takes under 3 minutes with vsite.' },
        { q: 'Can the AI read handwritten menus?', a: 'The AI works best on printed menus. Handwritten menus can be read but may require manual correction. For best results, use a clear printed menu photo taken in good lighting.' },
        { q: 'Does it work for Tamil-language menus?', a: 'Yes. vsite\'s AI is the only menu builder in India that reads Tamil script reliably. Mixed Tamil-English menus are also supported — common in Chennai, Coimbatore, and Madurai restaurants.' },
        { q: 'What if the AI gets something wrong?', a: 'You can edit anything in the dashboard after setup — prices, names, categories, photos. Most restaurants find the AI gets 90% right and they tweak the remaining 10% in a few minutes.' },
    ],
};

export const restaurantMenuSoftwarePage: SeoLandingData = {
    slug: 'restaurant-menu-software',
    h1: 'Restaurant Menu Software in India 2026',
    subtitle:
        'Modern restaurant menu software designed for India — QR code menus, AI food photos, Tamil support, UPI payment, and zero commission. ₹399/month with a 14-day free trial.',
    features: [
        { icon: 'qr_code_2', title: 'QR Code Menu', description: 'Generate unique QR codes for every table. Customers scan and order from their phone.' },
        { icon: 'auto_awesome', title: 'AI Food Photos', description: 'Every menu item gets a professional food photo generated automatically.' },
        { icon: 'storefront', title: 'Multi-Store Support', description: 'Run multiple outlets from one vsite account. Switch between stores in the dashboard.' },
        { icon: 'receipt', title: 'Order Management', description: 'See orders on a live kitchen dashboard. Mark items ready, completed, or out of stock.' },
        { icon: 'inventory_2', title: 'Menu Management', description: 'Add dishes, change prices, and organise categories — all changes are real-time.' },
        { icon: 'analytics', title: 'Reports & Insights', description: 'Track which items sell, at what times, and which customers come back.' },
    ],
    content: [
        { type: 'p', text: 'vsite is restaurant menu software purpose-built for Indian restaurants — especially in Tamil Nadu. It combines QR code menus, AI food photo generation, UPI payment, and real-time menu management into a single ₹399/month subscription. No commission, no POS hardware, no 2-day onboarding.' },
        { type: 'h2', text: 'What Restaurant Menu Software Should Do' },
        { type: 'ul', items: [
            'Let customers see your menu instantly via QR code',
            'Show professional food photos that drive higher order values',
            'Support price/item updates in real time (no reprinting)',
            'Accept UPI payments at the table without a POS machine',
            'Generate clean reports on orders, revenue, and customer patterns',
            'Work in your customers\' preferred language (Tamil for South Indian markets)',
        ]},
        { type: 'h2', text: 'How vsite Compares to Petpooja, DotPe, and Others' },
        { type: 'table', headers: ['Capability', 'vsite', 'Petpooja', 'DotPe'], rows: [
            ['QR code menu', 'Yes', 'Yes (add-on)', 'Yes'],
            ['AI food photos', 'Yes', 'No', 'No'],
            ['Tamil support', 'Native', 'Partial', 'No'],
            ['Full POS / billing', 'No', 'Yes', 'Partial'],
            ['Setup time', '3 min', '1–2 days', 'Days'],
            ['Price', '₹399/mo', '₹10,000+/yr + 1.5%', 'Commission-based'],
            ['Best for', 'SMB restaurants in TN', 'Mid-large chains', 'National chains'],
        ]},
        { type: 'callout', text: 'If you run a tiffin centre, hotel, cafe, or cloud kitchen in Tamil Nadu — vsite is the most affordable, fastest-to-launch menu software available in India today.' },
    ],
    relatedLinks: [
        { label: 'QR Code Menu →', href: '/qr-menu' },
        { label: 'Digital Menu for Restaurants in India →', href: '/digital-menu-india' },
        { label: 'AI Menu Builder →', href: '/ai-menu-builder' },
        { label: 'Pricing →', href: '/pricing' },
        { label: 'Features →', href: '/features' },
        { label: 'vsite vs Petpooja →', href: '/blog/vsite-vs-petpooja' },
        { label: 'Best Restaurant Software India 2026 →', href: '/blog/best-digital-menu-software-india-2026' },
    ],
    faqs: [
        { q: 'What is restaurant menu software?', a: 'Restaurant menu software lets you create, publish, and manage your restaurant\'s menu digitally. Modern options like vsite generate a QR code that customers scan to view the menu on their phone, with features like food photos, real-time price updates, and direct ordering.' },
        { q: 'How much does restaurant menu software cost in India?', a: 'Restaurant menu software in India ranges from free (basic tools with no photos or branding) to ₹10,000+ per year (full POS systems). vsite costs ₹399/month with a one-time setup fee of ₹1,999 — including AI food photos, QR codes, NFC cards, and Tamil support.' },
        { q: 'Do I need a POS machine to use vsite?', a: 'No. vsite works entirely from your phone or browser. Customers order and pay from their own phone via UPI. You see orders on a kitchen dashboard. No POS terminal, no card reader, no extra hardware.' },
        { q: 'Can I run multiple restaurants from one account?', a: 'Yes. vsite supports multiple stores under one login. Each store gets its own URL, QR code, and menu. You switch between stores in the dashboard.' },
        { q: 'Is there a free trial?', a: 'Yes. vsite offers a 14-day free trial with no credit card required. You can set up your full digital menu and test it with customers before paying anything.' },
    ],
};
